services:
  - type: web
    name: sirapope-schoolie-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # You'll need to set this manually in Render dashboard
    plan: free 