services:
  - type: web
    name: sirapope-schoolie-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # You'll need to set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false # Set this in Render dashboard
      - key: ROOT_ADMIN_EMAIL
        sync: false # Set this in Render dashboard
      - key: ROOT_ADMIN_PASSWORD
        sync: false # Set this in Render dashboard
    plan: free 