-- AlterTable
ALTER TABLE "AcademyMember" ADD COLUMN     "memberIncome" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "memberLevel" DOUBLE PRECISION NOT NULL DEFAULT 3.0,
ADD COLUMN     "memberStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
